(define (make-account blance password)
  (define (withdraw amount)
    (if (>= blance amount)
        (begin (set! blance (- blance amount))
               blance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! blance (+ blance amount))
          blance)
  (define (dispatch p m)
    (cond ((not (eq? p password)) error "Incorrect password -- MAKE-ACCOUNT")
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
 dispatch)

(define acc (make-account 100 'secret-password))

((acc 'secret-password 'withdraw) 40)
