(define (make-account blance password)
  (define error-count 0)
  (define (withdraw amount)
    (if (>= blance amount)
        (begin (set! blance (- blance amount))
               blance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! blance (+ blance amount))
          blance)

  (define (call-the-cops) (error "Call the cops -- MAKE-ACCOUNT"))

  (define (dispatch p m)
    (cond ((not (eq? p password)) (set! error-count (+ error-count 1))
                (if (>= error-count 7)
                    (lambda (v) (call-the-cops))
                    (lambda (v) "Incorrect password")))
          ((>= error-count 7) call-the-cops)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
 dispatch)

(define acc (make-account 100 'secret-password))

((acc 'secret-password1 'withdraw) 40)
((acc 'secret-password2 'withdraw) 40)
((acc 'secret-password3 'withdraw) 40)
((acc 'secret-password4 'withdraw) 40)
((acc 'secret-password5 'withdraw) 40)
((acc 'secret-password6 'withdraw) 40)
((acc 'secret-password7 'withdraw) 40)
