(define (make-account blance password)
  (define (withdraw amount)
    (if (>= blance amount)
        (begin (set! blance (- blance amount))
               blance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! blance (+ blance amount))
          blance)
  (define (dispatch p m)
    (cond ((not (eq? p password)) error "Incorrect password -- MAKE-ACCOUNT")
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
 dispatch)

(define (make-joint account account-password new-password)
  (define (dispatch password m)
    (if (eq? password new-password)
        (account account-password m)
        (error "Incorrect password" account-password)))
  dispatch)


(define peter-acc (make-account 100 'secret-password))
((peter-acc 'secret-password 'withdraw) 10)

(define paul-acc (make-joint peter-acc 'secret-password 'open-sesame))
((paul-acc 'open-sesame 'withdraw) 20)
